### ISSUE TITLE
Problem creating more than one uploader per page

### ISSUE THREAD

**Issue by dnviti** [trent-/apex-ajax-upload#1]
There is an important problem about this plugin: when i try to create more than one AJAX Upload item on a single page, the last created element will overwrite che configuration settings of the ones which comes before.
It is an enormous problem, can you try to fix this?

**Comment by tschf** [comment]
Hi - this was an experimental plugin from years back. I may suggest the drop zone plugin which may serve your needs: https://github.com/Dani3lSun/apex-plugin-dropzone
